// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8bS9an1nHfZsjLBuCCZ_9rMJj_eXhJQI',
    appId: '1:1001071502369:android:7fc5abff04878fd49eef60',
    messagingSenderId: '1001071502369',
    projectId: 'summer-project-6fcb7',
    databaseURL: 'https://summer-project-6fcb7-default-rtdb.firebaseio.com',
    storageBucket: 'summer-project-6fcb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATfouzGsjKrMDZQ9h1bhgSh8B0CW4e_0c',
    appId: '1:1001071502369:ios:5312d1b331fea6f49eef60',
    messagingSenderId: '1001071502369',
    projectId: 'summer-project-6fcb7',
    databaseURL: 'https://summer-project-6fcb7-default-rtdb.firebaseio.com',
    storageBucket: 'summer-project-6fcb7.appspot.com',
    iosBundleId: 'com.example.demo',
  );
}
